### ISSUE TITLE
a question about simplE_ignr.py

### ISSUE THREAD

**Issue by zhangzhaocs** [Mehran-k/SimplE#2]
I really like this work, but I have one thing confused.
In the 34th line of simplE_ignr.py, you use the code "self.labels = tf.tile(self.y, [2])", why do you use this code (what's its effect), and why don't you use the code in simplE_avg.py?
Looking forward to your kind feedback.

**Comment by Mehran-k** [comment]
Thanks for your interest in my work.
Suppose we have a mini-batch whose X is:
(E1, R1, E2) 
(E2, R2, E3)
and whose Y is 
+1
-1
(That is, E1 has relation R1 with E2 and E2 does not have relation R2 with E3).

In SimplE-ignr, I augment my X by adding the inverses in lines 22-24 (see the concats) as:
(E1, R1, E2) 
(E2, R2, E3)
(E2, R1_inv, E2) 
(E3, R2_inv, E2)

I also duplicate/tile my Y as follows:
+1
-1
+1
-1
as the label for the triple and its inverse is the same. 
In SimplE-avg, I don't have to do this because the similarity function is the average of the two predictions.

Hope this helps.

**Comment by zhangzhaocs** [comment]
Thanks for your feedback!
My confusion has been completely eliminated.

**Comment by Mehran-k** [comment]
Your welcome! Closing the issue.
